### Delete a product
DELETE {{host}}/api/products/{{productId}}
Content-Type: application/json

> {%
    client.test("Status is 200", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.test("Response is successful", function() {
        client.assert(response.body.success === true, "Expected success to be true");
    });

    client.test("Delete message returned", function() {
        client.assert(response.body.data.message === "Product deleted", "Expected deletion message");
    });
%}

###
