### GET products
GET {{host}}/products
Content-Type: application/json

> {%
    client.test("Status is 200", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.test("Response is successful", function() {
        client.assert(response.body.success === true, "Expected success to be true");
    });

    client.test("Data is an array", function() {
        client.assert(Array.isArray(response.body.data), "Expected data to be an array");
    });
%}

###
