### Update a category
PUT {{host}}/api/categories/{{categoryId}}
Content-Type: application/json

{
    "name": "Snack",
    "description": "Chocolate, crackers, etc."
}

> {%
    client.test("Status is 200", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.test("Response is successful", function() {
        client.assert(response.body.success === true, "Expected success to be true");
    });

    client.test("Name was updated", function() {
        client.assert(response.body.data.name === "Snack", "Expected name 'Snack'");
    });

    client.test("Description was updated", function() {
        client.assert(response.body.data.description === "Chocolate, crackers, etc.", "Expected updated description");
    });
%}

###
